// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNonceRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub address: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetNonceResponse {
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProofStatusRequest {
    #[prost(string, tag = "1")]
    pub proof_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProofStatusResponse {
    #[prost(enumeration = "ProofStatus", tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub proof_url: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProofRequestsRequest {
    #[prost(enumeration = "ProofStatus", tag = "1")]
    pub status: i32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetProofRequestsResponse {
    #[prost(string, repeated, tag = "1")]
    pub proof_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateProofRequest {
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
    #[prost(uint64, tag = "2")]
    pub deadline: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateProofResponse {
    #[prost(string, tag = "1")]
    pub proof_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub program_url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub stdin_url: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitProofRequest {
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
    #[prost(string, tag = "2")]
    pub proof_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitProofResponse {}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimProofRequest {
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
    #[prost(string, tag = "2")]
    pub proof_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClaimProofResponse {
    #[prost(string, tag = "1")]
    pub program_artifact_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub stdin_artifact_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub proof_artifact_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FulfillProofRequest {
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
    #[prost(string, tag = "2")]
    pub proof_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FulfillProofResponse {
    #[prost(uint64, tag = "1")]
    pub proving_seconds: u64,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayProofRequest {
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
    #[prost(string, tag = "2")]
    pub proof_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub chain_id: u32,
    #[prost(bytes = "vec", tag = "4")]
    pub verifier: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub callback: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub callback_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "7")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelayProofResponse {
    #[prost(string, tag = "1")]
    pub tx_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRelayStatusRequest {
    #[prost(string, tag = "1")]
    pub tx_id: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRelayStatusResponse {
    #[prost(enumeration = "TransactionStatus", tag = "1")]
    pub status: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub simulation_url: ::prost::alloc::string::String,
}
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::prost::Enumeration,
)]
#[repr(i32)]
pub enum ProofStatus {
    ProofUnspecifiedStatus = 0,
    ProofPreparing = 1,
    ProofRequested = 2,
    ProofClaimed = 3,
    ProofFulfilled = 4,
    ProofFailed = 5,
}
impl ProofStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ProofStatus::ProofUnspecifiedStatus => "PROOF_UNSPECIFIED_STATUS",
            ProofStatus::ProofPreparing => "PROOF_PREPARING",
            ProofStatus::ProofRequested => "PROOF_REQUESTED",
            ProofStatus::ProofClaimed => "PROOF_CLAIMED",
            ProofStatus::ProofFulfilled => "PROOF_FULFILLED",
            ProofStatus::ProofFailed => "PROOF_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROOF_UNSPECIFIED_STATUS" => Some(Self::ProofUnspecifiedStatus),
            "PROOF_PREPARING" => Some(Self::ProofPreparing),
            "PROOF_REQUESTED" => Some(Self::ProofRequested),
            "PROOF_CLAIMED" => Some(Self::ProofClaimed),
            "PROOF_FULFILLED" => Some(Self::ProofFulfilled),
            "PROOF_FAILED" => Some(Self::ProofFailed),
            _ => None,
        }
    }
}
#[derive(
    serde::Serialize,
    serde::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    PartialOrd,
    Ord,
    ::prost::Enumeration,
)]
#[repr(i32)]
pub enum TransactionStatus {
    TransactionUnspecifiedStatus = 0,
    TransactionScheduled = 1,
    TransactionBroadcasted = 2,
    TransactionTimedout = 3,
    TransactionFailed = 4,
    TransactionFinalized = 5,
}
impl TransactionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TransactionStatus::TransactionUnspecifiedStatus => "TRANSACTION_UNSPECIFIED_STATUS",
            TransactionStatus::TransactionScheduled => "TRANSACTION_SCHEDULED",
            TransactionStatus::TransactionBroadcasted => "TRANSACTION_BROADCASTED",
            TransactionStatus::TransactionTimedout => "TRANSACTION_TIMEDOUT",
            TransactionStatus::TransactionFailed => "TRANSACTION_FAILED",
            TransactionStatus::TransactionFinalized => "TRANSACTION_FINALIZED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRANSACTION_UNSPECIFIED_STATUS" => Some(Self::TransactionUnspecifiedStatus),
            "TRANSACTION_SCHEDULED" => Some(Self::TransactionScheduled),
            "TRANSACTION_BROADCASTED" => Some(Self::TransactionBroadcasted),
            "TRANSACTION_TIMEDOUT" => Some(Self::TransactionTimedout),
            "TRANSACTION_FAILED" => Some(Self::TransactionFailed),
            "TRANSACTION_FINALIZED" => Some(Self::TransactionFinalized),
            _ => None,
        }
    }
}
pub const SERVICE_FQN: &str = "/network.NetworkService";
#[twirp::async_trait::async_trait]
pub trait NetworkService {
    async fn get_nonce(
        &self,
        ctx: twirp::Context,
        req: GetNonceRequest,
    ) -> Result<GetNonceResponse, twirp::TwirpErrorResponse>;
    async fn get_proof_status(
        &self,
        ctx: twirp::Context,
        req: GetProofStatusRequest,
    ) -> Result<GetProofStatusResponse, twirp::TwirpErrorResponse>;
    async fn get_proof_requests(
        &self,
        ctx: twirp::Context,
        req: GetProofRequestsRequest,
    ) -> Result<GetProofRequestsResponse, twirp::TwirpErrorResponse>;
    async fn get_relay_status(
        &self,
        ctx: twirp::Context,
        req: GetRelayStatusRequest,
    ) -> Result<GetRelayStatusResponse, twirp::TwirpErrorResponse>;
    async fn create_proof(
        &self,
        ctx: twirp::Context,
        req: CreateProofRequest,
    ) -> Result<CreateProofResponse, twirp::TwirpErrorResponse>;
    async fn submit_proof(
        &self,
        ctx: twirp::Context,
        req: SubmitProofRequest,
    ) -> Result<SubmitProofResponse, twirp::TwirpErrorResponse>;
    async fn claim_proof(
        &self,
        ctx: twirp::Context,
        req: ClaimProofRequest,
    ) -> Result<ClaimProofResponse, twirp::TwirpErrorResponse>;
    async fn fulfill_proof(
        &self,
        ctx: twirp::Context,
        req: FulfillProofRequest,
    ) -> Result<FulfillProofResponse, twirp::TwirpErrorResponse>;
    async fn relay_proof(
        &self,
        ctx: twirp::Context,
        req: RelayProofRequest,
    ) -> Result<RelayProofResponse, twirp::TwirpErrorResponse>;
}
pub fn router<T>(api: std::sync::Arc<T>) -> twirp::Router
where
    T: NetworkService + Send + Sync + 'static,
{
    twirp::details::TwirpRouterBuilder::new(api)
        .route(
            "/GetNonce",
            |api: std::sync::Arc<T>, ctx: twirp::Context, req: GetNonceRequest| async move {
                api.get_nonce(ctx, req).await
            },
        )
        .route(
            "/GetProofStatus",
            |api: std::sync::Arc<T>, ctx: twirp::Context, req: GetProofStatusRequest| async move {
                api.get_proof_status(ctx, req).await
            },
        )
        .route(
            "/GetProofRequests",
            |api: std::sync::Arc<T>, ctx: twirp::Context, req: GetProofRequestsRequest| async move {
                api.get_proof_requests(ctx, req).await
            },
        )
        .route(
            "/GetRelayStatus",
            |api: std::sync::Arc<T>, ctx: twirp::Context, req: GetRelayStatusRequest| async move {
                api.get_relay_status(ctx, req).await
            },
        )
        .route(
            "/CreateProof",
            |api: std::sync::Arc<T>, ctx: twirp::Context, req: CreateProofRequest| async move {
                api.create_proof(ctx, req).await
            },
        )
        .route(
            "/SubmitProof",
            |api: std::sync::Arc<T>, ctx: twirp::Context, req: SubmitProofRequest| async move {
                api.submit_proof(ctx, req).await
            },
        )
        .route(
            "/ClaimProof",
            |api: std::sync::Arc<T>, ctx: twirp::Context, req: ClaimProofRequest| async move {
                api.claim_proof(ctx, req).await
            },
        )
        .route(
            "/FulfillProof",
            |api: std::sync::Arc<T>, ctx: twirp::Context, req: FulfillProofRequest| async move {
                api.fulfill_proof(ctx, req).await
            },
        )
        .route(
            "/RelayProof",
            |api: std::sync::Arc<T>, ctx: twirp::Context, req: RelayProofRequest| async move {
                api.relay_proof(ctx, req).await
            },
        )
        .build()
}
#[twirp::async_trait::async_trait]
pub trait NetworkServiceClient: Send + Sync + std::fmt::Debug {
    async fn get_nonce(&self, req: GetNonceRequest)
        -> Result<GetNonceResponse, twirp::ClientError>;
    async fn get_proof_status(
        &self,
        req: GetProofStatusRequest,
    ) -> Result<GetProofStatusResponse, twirp::ClientError>;
    async fn get_proof_requests(
        &self,
        req: GetProofRequestsRequest,
    ) -> Result<GetProofRequestsResponse, twirp::ClientError>;
    async fn get_relay_status(
        &self,
        req: GetRelayStatusRequest,
    ) -> Result<GetRelayStatusResponse, twirp::ClientError>;
    async fn create_proof(
        &self,
        req: CreateProofRequest,
    ) -> Result<CreateProofResponse, twirp::ClientError>;
    async fn submit_proof(
        &self,
        req: SubmitProofRequest,
    ) -> Result<SubmitProofResponse, twirp::ClientError>;
    async fn claim_proof(
        &self,
        req: ClaimProofRequest,
    ) -> Result<ClaimProofResponse, twirp::ClientError>;
    async fn fulfill_proof(
        &self,
        req: FulfillProofRequest,
    ) -> Result<FulfillProofResponse, twirp::ClientError>;
    async fn relay_proof(
        &self,
        req: RelayProofRequest,
    ) -> Result<RelayProofResponse, twirp::ClientError>;
}
#[twirp::async_trait::async_trait]
impl NetworkServiceClient for twirp::client::Client {
    async fn get_nonce(
        &self,
        req: GetNonceRequest,
    ) -> Result<GetNonceResponse, twirp::ClientError> {
        let url = self.base_url.join("network.NetworkService/GetNonce")?;
        self.request(url, req).await
    }
    async fn get_proof_status(
        &self,
        req: GetProofStatusRequest,
    ) -> Result<GetProofStatusResponse, twirp::ClientError> {
        let url = self
            .base_url
            .join("network.NetworkService/GetProofStatus")?;
        self.request(url, req).await
    }
    async fn get_proof_requests(
        &self,
        req: GetProofRequestsRequest,
    ) -> Result<GetProofRequestsResponse, twirp::ClientError> {
        let url = self
            .base_url
            .join("network.NetworkService/GetProofRequests")?;
        self.request(url, req).await
    }
    async fn get_relay_status(
        &self,
        req: GetRelayStatusRequest,
    ) -> Result<GetRelayStatusResponse, twirp::ClientError> {
        let url = self
            .base_url
            .join("network.NetworkService/GetRelayStatus")?;
        self.request(url, req).await
    }
    async fn create_proof(
        &self,
        req: CreateProofRequest,
    ) -> Result<CreateProofResponse, twirp::ClientError> {
        let url = self.base_url.join("network.NetworkService/CreateProof")?;
        self.request(url, req).await
    }
    async fn submit_proof(
        &self,
        req: SubmitProofRequest,
    ) -> Result<SubmitProofResponse, twirp::ClientError> {
        let url = self.base_url.join("network.NetworkService/SubmitProof")?;
        self.request(url, req).await
    }
    async fn claim_proof(
        &self,
        req: ClaimProofRequest,
    ) -> Result<ClaimProofResponse, twirp::ClientError> {
        let url = self.base_url.join("network.NetworkService/ClaimProof")?;
        self.request(url, req).await
    }
    async fn fulfill_proof(
        &self,
        req: FulfillProofRequest,
    ) -> Result<FulfillProofResponse, twirp::ClientError> {
        let url = self.base_url.join("network.NetworkService/FulfillProof")?;
        self.request(url, req).await
    }
    async fn relay_proof(
        &self,
        req: RelayProofRequest,
    ) -> Result<RelayProofResponse, twirp::ClientError> {
        let url = self.base_url.join("network.NetworkService/RelayProof")?;
        self.request(url, req).await
    }
}
